# Generated by Django 5.2.4 on 2025-08-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_video_options_video_category_video_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={},
        ),
        migrations.RemoveField(
            model_name="video",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="video",
            name="hls_master_playlist",
        ),
        migrations.RemoveField(
            model_name="video",
            name="processing_status",
        ),
        migrations.RemoveField(
            model_name="video",
            name="video_file",
        ),
        migrations.AddField(
            model_name="video",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=256),
        ),
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name="VideoQuality",
        ),
    ]
