# Generated by Django 5.2.4 on 2025-11-07 19:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_video_options_remove_video_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True
            ),
        ),
    ]
