# Generated by Django 5.2.4 on 2025-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="hls_generated",
            field=models.BooleanField(default=False),
        ),
    ]
