# Generated by Django 5.2.4 on 2025-11-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_video_hls_generated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="hls_generated",
        ),
    ]
